### PR TITLE
test: smart-contract and its transaction service

### PR DESCRIPTION
**Pull request by lukebrichey**
## Creation of New Test Suite for `smart-contract.service.ts` and `transaction.service.ts`

This pull request introduces a brand new test suite for the `SmartContractService`, which contains functionality to silence the log helper output for more readable tests. Additionally, it also introduces a new test suite for the accompanying `TransactionService`. This PR also contributes towards Issue #50, improving test coverage by ~5%. Here are the main features:

### Test Suite Introduction

An entirely new test suite has been created for `SmartContractService`. This test suite includes comprehensive test coverage for the following methods:

1. **getGasFees**

2. **mintVoucher**

3. **getVoucherById**

4. **getAllVouchers**

5. **transferVoucher**

6. **alterVoucher**

As well as a test suite for `TransactionService`, covering the following methods:

1. **getAllTransactionHistory**

2. **getTransactionHistoryBySenderId**

### Log Helper Output Silencing

To improve test readability, this PR also includes changes to silence the log helper output when running the test suite for `SmartContractService` contained in `smart-contract.service.test.ts`.

In the test suite, the `console.error` output from the `logError` helper and `console.log` output from the `logInfo` helper is silenced. This is done using jest's `spyOn` function to mock empty implementations of `logError` and `logInfo`. Note that this causes error output from the methods to be silenced, which could make debugging failing assertions more difficult. It may be worth refactoring the error messages in `smart-contract.service.test.ts` to align with the rest of the codebase and avoid this issue.

Review and feedback is much appreciated!

### CODE REVIEW

**Comment by lukebrichey** [comment]
I will start working on tests for `transaction.service` as well. I will likely extend this PR later on to include this test suite since these services are both providers in the smart contract module.

**Comment by lukebrichey** [comment]
Note: This PR has now been extended to include `transaction.service.test.ts`, and has been edited to include those changes as well.

**Review by abhiShandy — APPROVED** [review]

**Comment by abhiShandy** [comment]
Keep PR small. It's better to limit it to few 100 lines of code or less than 10 files.

**Comment by lukebrichey** [comment]
Sorry, will do that next time.

**Pull request merged**
